"""empty message

Revision ID: 7462e421e436
Revises: 
Create Date: 2023-04-05 21:40:20.168130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7462e421e436'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Jobs', sa.Column('edge_finish', sa.String(), nullable=True))
    op.alter_column('Jobs', 'contact_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Jobs', 'contact_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Jobs', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Jobs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Jobs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Jobs', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Jobs', 'contact_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Jobs', 'contact_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('Jobs', 'edge_finish')
    # ### end Alembic commands ###
