"""empty message

Revision ID: a6bcf9d6b93f
Revises: c9d2600b3124
Create Date: 2023-04-15 14:24:43.368243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6bcf9d6b93f'
down_revision = 'c9d2600b3124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Inventory_sink_id_fkey', 'Inventory', type_='foreignkey')
    op.create_foreign_key(None, 'Inventory', 'Sinks', ['sink_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Inventory', type_='foreignkey')
    op.create_foreign_key('Inventory_sink_id_fkey', 'Inventory', 'Sinks', ['sink_id'], ['id'])
    # ### end Alembic commands ###
