"""empty message

Revision ID: c9d2600b3124
Revises: daf4ef7c9032
Create Date: 2023-04-09 08:15:56.195124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d2600b3124'
down_revision = 'daf4ef7c9032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Inventory', sa.Column('sink_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Inventory', 'Sinks', ['sink_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Inventory', type_='foreignkey')
    op.drop_column('Inventory', 'sink_id')
    # ### end Alembic commands ###
