"""empty message

Revision ID: daf4ef7c9032
Revises: 7462e421e436
Create Date: 2023-04-05 22:47:08.974723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf4ef7c9032'
down_revision = '7462e421e436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Jobs', sa.Column('job_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Jobs', 'job_name')
    # ### end Alembic commands ###
